// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// amh_montoril_cpp
List amh_montoril_cpp(NumericVector y, int N, double mu_01, double sigma2_01, double mu_02, double sigma2_02, double nu_01, double eta_01, double nu_02, double eta_02, NumericVector theta1, NumericVector theta2, double theta_01, double theta_02, double W1, double W2, double ac_ref, NumericVector varsigma2, bool verbose, int print_every);
RcppExport SEXP _PoissonLTDM_amh_montoril_cpp(SEXP ySEXP, SEXP NSEXP, SEXP mu_01SEXP, SEXP sigma2_01SEXP, SEXP mu_02SEXP, SEXP sigma2_02SEXP, SEXP nu_01SEXP, SEXP eta_01SEXP, SEXP nu_02SEXP, SEXP eta_02SEXP, SEXP theta1SEXP, SEXP theta2SEXP, SEXP theta_01SEXP, SEXP theta_02SEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP ac_refSEXP, SEXP varsigma2SEXP, SEXP verboseSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type mu_01(mu_01SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_01(sigma2_01SEXP);
    Rcpp::traits::input_parameter< double >::type mu_02(mu_02SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_02(sigma2_02SEXP);
    Rcpp::traits::input_parameter< double >::type nu_01(nu_01SEXP);
    Rcpp::traits::input_parameter< double >::type eta_01(eta_01SEXP);
    Rcpp::traits::input_parameter< double >::type nu_02(nu_02SEXP);
    Rcpp::traits::input_parameter< double >::type eta_02(eta_02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< double >::type theta_01(theta_01SEXP);
    Rcpp::traits::input_parameter< double >::type theta_02(theta_02SEXP);
    Rcpp::traits::input_parameter< double >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< double >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< double >::type ac_ref(ac_refSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type varsigma2(varsigma2SEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    rcpp_result_gen = Rcpp::wrap(amh_montoril_cpp(y, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta_01, theta_02, W1, W2, ac_ref, varsigma2, verbose, print_every));
    return rcpp_result_gen;
END_RCPP
}
// rhat_ess_fast
List rhat_ess_fast(NumericVector arr_r, int n_threads);
RcppExport SEXP _PoissonLTDM_rhat_ess_fast(SEXP arr_rSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr_r(arr_rSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rhat_ess_fast(arr_r, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// test_tridiag_solve
List test_tridiag_solve(NumericVector d, NumericVector e, NumericVector b, NumericVector w_for_Lt);
RcppExport SEXP _PoissonLTDM_test_tridiag_solve(SEXP dSEXP, SEXP eSEXP, SEXP bSEXP, SEXP w_for_LtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w_for_Lt(w_for_LtSEXP);
    rcpp_result_gen = Rcpp::wrap(test_tridiag_solve(d, e, b, w_for_Lt));
    return rcpp_result_gen;
END_RCPP
}
// test_chan_assembly
List test_chan_assembly(NumericVector theta1, double phi1, double phi2, double mu_02, double sigma2_02, double theta_01);
RcppExport SEXP _PoissonLTDM_test_chan_assembly(SEXP theta1SEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP mu_02SEXP, SEXP sigma2_02SEXP, SEXP theta_01SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< double >::type mu_02(mu_02SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_02(sigma2_02SEXP);
    Rcpp::traits::input_parameter< double >::type theta_01(theta_01SEXP);
    rcpp_result_gen = Rcpp::wrap(test_chan_assembly(theta1, phi1, phi2, mu_02, sigma2_02, theta_01));
    return rcpp_result_gen;
END_RCPP
}
// pg_as_cpp
List pg_as_cpp(NumericVector y, int K, int N, double mu_01, double sigma2_01, double mu_02, double sigma2_02, double nu_01, double eta_01, double nu_02, double eta_02, NumericVector theta1, NumericVector theta2, double theta_01, double theta_02, double W1, double W2, bool verbose, int print_every);
RcppExport SEXP _PoissonLTDM_pg_as_cpp(SEXP ySEXP, SEXP KSEXP, SEXP NSEXP, SEXP mu_01SEXP, SEXP sigma2_01SEXP, SEXP mu_02SEXP, SEXP sigma2_02SEXP, SEXP nu_01SEXP, SEXP eta_01SEXP, SEXP nu_02SEXP, SEXP eta_02SEXP, SEXP theta1SEXP, SEXP theta2SEXP, SEXP theta_01SEXP, SEXP theta_02SEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP verboseSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type mu_01(mu_01SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_01(sigma2_01SEXP);
    Rcpp::traits::input_parameter< double >::type mu_02(mu_02SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_02(sigma2_02SEXP);
    Rcpp::traits::input_parameter< double >::type nu_01(nu_01SEXP);
    Rcpp::traits::input_parameter< double >::type eta_01(eta_01SEXP);
    Rcpp::traits::input_parameter< double >::type nu_02(nu_02SEXP);
    Rcpp::traits::input_parameter< double >::type eta_02(eta_02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< double >::type theta_01(theta_01SEXP);
    Rcpp::traits::input_parameter< double >::type theta_02(theta_02SEXP);
    Rcpp::traits::input_parameter< double >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< double >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    rcpp_result_gen = Rcpp::wrap(pg_as_cpp(y, K, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta_01, theta_02, W1, W2, verbose, print_every));
    return rcpp_result_gen;
END_RCPP
}
// sir_collapsed_cpp
List sir_collapsed_cpp(NumericVector y, int R_prerun, int N, double mu_01, double sigma2_01, double mu_02, double sigma2_02, double nu_01, double eta_01, double nu_02, double eta_02, NumericVector theta1, NumericVector theta2, NumericVector theta1_tilde, double theta_01, double theta_02, double W1, double W2, int M_is_lik, int M_sir_theta1, int M_irls_max, double tol, bool verbose, int print_every);
RcppExport SEXP _PoissonLTDM_sir_collapsed_cpp(SEXP ySEXP, SEXP R_prerunSEXP, SEXP NSEXP, SEXP mu_01SEXP, SEXP sigma2_01SEXP, SEXP mu_02SEXP, SEXP sigma2_02SEXP, SEXP nu_01SEXP, SEXP eta_01SEXP, SEXP nu_02SEXP, SEXP eta_02SEXP, SEXP theta1SEXP, SEXP theta2SEXP, SEXP theta1_tildeSEXP, SEXP theta_01SEXP, SEXP theta_02SEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP M_is_likSEXP, SEXP M_sir_theta1SEXP, SEXP M_irls_maxSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type R_prerun(R_prerunSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type mu_01(mu_01SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_01(sigma2_01SEXP);
    Rcpp::traits::input_parameter< double >::type mu_02(mu_02SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_02(sigma2_02SEXP);
    Rcpp::traits::input_parameter< double >::type nu_01(nu_01SEXP);
    Rcpp::traits::input_parameter< double >::type eta_01(eta_01SEXP);
    Rcpp::traits::input_parameter< double >::type nu_02(nu_02SEXP);
    Rcpp::traits::input_parameter< double >::type eta_02(eta_02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta1_tilde(theta1_tildeSEXP);
    Rcpp::traits::input_parameter< double >::type theta_01(theta_01SEXP);
    Rcpp::traits::input_parameter< double >::type theta_02(theta_02SEXP);
    Rcpp::traits::input_parameter< double >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< double >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< int >::type M_is_lik(M_is_likSEXP);
    Rcpp::traits::input_parameter< int >::type M_sir_theta1(M_sir_theta1SEXP);
    Rcpp::traits::input_parameter< int >::type M_irls_max(M_irls_maxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    rcpp_result_gen = Rcpp::wrap(sir_collapsed_cpp(y, R_prerun, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta1_tilde, theta_01, theta_02, W1, W2, M_is_lik, M_sir_theta1, M_irls_max, tol, verbose, print_every));
    return rcpp_result_gen;
END_RCPP
}
// sir_laplace_cpp
List sir_laplace_cpp(NumericVector y, int N, double mu_01, double sigma2_01, double mu_02, double sigma2_02, double nu_01, double eta_01, double nu_02, double eta_02, NumericVector theta1, NumericVector theta2, double theta_01, double theta_02, double W1, double W2, int M_irls_max, int M_is, double tol, bool verbose, int print_every);
RcppExport SEXP _PoissonLTDM_sir_laplace_cpp(SEXP ySEXP, SEXP NSEXP, SEXP mu_01SEXP, SEXP sigma2_01SEXP, SEXP mu_02SEXP, SEXP sigma2_02SEXP, SEXP nu_01SEXP, SEXP eta_01SEXP, SEXP nu_02SEXP, SEXP eta_02SEXP, SEXP theta1SEXP, SEXP theta2SEXP, SEXP theta_01SEXP, SEXP theta_02SEXP, SEXP W1SEXP, SEXP W2SEXP, SEXP M_irls_maxSEXP, SEXP M_isSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type mu_01(mu_01SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_01(sigma2_01SEXP);
    Rcpp::traits::input_parameter< double >::type mu_02(mu_02SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_02(sigma2_02SEXP);
    Rcpp::traits::input_parameter< double >::type nu_01(nu_01SEXP);
    Rcpp::traits::input_parameter< double >::type eta_01(eta_01SEXP);
    Rcpp::traits::input_parameter< double >::type nu_02(nu_02SEXP);
    Rcpp::traits::input_parameter< double >::type eta_02(eta_02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< double >::type theta_01(theta_01SEXP);
    Rcpp::traits::input_parameter< double >::type theta_02(theta_02SEXP);
    Rcpp::traits::input_parameter< double >::type W1(W1SEXP);
    Rcpp::traits::input_parameter< double >::type W2(W2SEXP);
    Rcpp::traits::input_parameter< int >::type M_irls_max(M_irls_maxSEXP);
    Rcpp::traits::input_parameter< int >::type M_is(M_isSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    rcpp_result_gen = Rcpp::wrap(sir_laplace_cpp(y, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta_01, theta_02, W1, W2, M_irls_max, M_is, tol, verbose, print_every));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PoissonLTDM_amh_montoril_cpp", (DL_FUNC) &_PoissonLTDM_amh_montoril_cpp, 20},
    {"_PoissonLTDM_rhat_ess_fast", (DL_FUNC) &_PoissonLTDM_rhat_ess_fast, 2},
    {"_PoissonLTDM_test_tridiag_solve", (DL_FUNC) &_PoissonLTDM_test_tridiag_solve, 4},
    {"_PoissonLTDM_test_chan_assembly", (DL_FUNC) &_PoissonLTDM_test_chan_assembly, 6},
    {"_PoissonLTDM_pg_as_cpp", (DL_FUNC) &_PoissonLTDM_pg_as_cpp, 19},
    {"_PoissonLTDM_sir_collapsed_cpp", (DL_FUNC) &_PoissonLTDM_sir_collapsed_cpp, 24},
    {"_PoissonLTDM_sir_laplace_cpp", (DL_FUNC) &_PoissonLTDM_sir_laplace_cpp, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_PoissonLTDM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
