# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

amh_montoril_cpp <- function(y, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta_01, theta_02, W1, W2, ac_ref, varsigma2, verbose = TRUE, print_every = 1000L) {
    .Call(`_PoissonLTDM_amh_montoril_cpp`, y, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta_01, theta_02, W1, W2, ac_ref, varsigma2, verbose, print_every)
}

rhat_ess_fast <- function(arr_r, n_threads = 0L) {
    .Call(`_PoissonLTDM_rhat_ess_fast`, arr_r, n_threads)
}

test_tridiag_solve <- function(d, e, b, w_for_Lt) {
    .Call(`_PoissonLTDM_test_tridiag_solve`, d, e, b, w_for_Lt)
}

test_chan_assembly <- function(theta1, phi1, phi2, mu_02, sigma2_02, theta_01) {
    .Call(`_PoissonLTDM_test_chan_assembly`, theta1, phi1, phi2, mu_02, sigma2_02, theta_01)
}

pg_as_cpp <- function(y, K, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta_01, theta_02, W1, W2, verbose = TRUE, print_every = 100L) {
    .Call(`_PoissonLTDM_pg_as_cpp`, y, K, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta_01, theta_02, W1, W2, verbose, print_every)
}

sir_collapsed_cpp <- function(y, R_prerun, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta1_tilde, theta_01, theta_02, W1, W2, M_is_lik, M_sir_theta1, M_irls_max, tol, verbose = TRUE, print_every = 1000L) {
    .Call(`_PoissonLTDM_sir_collapsed_cpp`, y, R_prerun, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta1_tilde, theta_01, theta_02, W1, W2, M_is_lik, M_sir_theta1, M_irls_max, tol, verbose, print_every)
}

sir_laplace_cpp <- function(y, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta_01, theta_02, W1, W2, M_irls_max, M_is, tol, verbose = TRUE, print_every = 1000L) {
    .Call(`_PoissonLTDM_sir_laplace_cpp`, y, N, mu_01, sigma2_01, mu_02, sigma2_02, nu_01, eta_01, nu_02, eta_02, theta1, theta2, theta_01, theta_02, W1, W2, M_irls_max, M_is, tol, verbose, print_every)
}

